import Head from "next/head";
import { useEffect, useState } from "react";
import { Grid, Loader } from "semantic-ui-react";
import styles from "../styles/Home.module.css";
import Content from "./components/comment";
import Recent from "./components/recent";

export default function Home() {
  const [loading, setLoading] = useState(true);

  useEffect(function () {
    setLoading(false);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextmatic | Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading ? (
          <>
            <Loader active />
          </>
        ) : (
          <div>
            <Grid columns="2" divided>
              <Grid.Row>
                <Grid.Column>
                  <Content />
                </Grid.Column>
                <Grid.Column>
                  <Recent />
                </Grid.Column>
              </Grid.Row>
            </Grid>
          </div>
        )}
      </main>
    </div>
  );
}
