import Head from "next/head";
import { Grid } from "semantic-ui-react";
import styles from "../styles/Home.module.css";
import Content from "./components/comment";
import Recent from "./components/recent";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextmatic | Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid columns="2" divided>
          <Grid.Row>
            <Grid.Column>
              <Content />
            </Grid.Column>
            <Grid.Column>
              <Recent />
            </Grid.Column>
          </Grid.Row>
        </Grid>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
